name: Create Release

on:
  create:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and compile
      run: make

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          This is a release for tag ${{ github.ref }}.
        draft: false
        prerelease: false

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compare-files-artifacts
        path: compare-files

    - name: Set output variable
      id: artifacts
      run: echo ::set-output name=artifacts::compare-files-artifacts
