name: Create Release with Compressed Artifacts

on:
  create:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and compile
        run: make

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is a sample release for tag ${{ github.ref }}.
          draft: false
          prerelease: false

      - name: Compress artifacts
        run: |
          tar czf compare-files-artifacts.tar.gz cf
          zip -r compare-files-artifacts.zip cf

      - name: Upload compressed artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: compare-files-artifacts.tar.gz
          asset_name: compare-files-artifacts.tar.gz
          asset_content_type: application/gzip

      - name: Upload compressed artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: compare-files-artifacts.zip
          asset_name: compare-files-artifacts.zip
          asset_content_type: application/zip
